FROM node:latest

WORKDIR /app
COPY . /app

VOLUME /app/botiumwork
VOLUME /app/testsets

ARG BOTIUMBOX_QUEUE_REDISURL=redis://redisuser:redispassword@redishost:redisport
ARG PRISMA_ENDPOINT=https://my-prisma-endpoint/demo/dev
ARG PRISMA_MANAGEMENT_API_SECRET=
ARG PRISMA_SECRET=myprismasecret123
ARG JWT_SECRET=myjwtsecret123

ENV BOTIUMBOX_QUEUE_REDISURL $BOTIUMBOX_QUEUE_REDISURL
ENV PRISMA_ENDPOINT $PRISMA_ENDPOINT
ENV PRISMA_MANAGEMENT_API_SECRET $PRISMA_MANAGEMENT_API_SECRET
ENV PRISMA_SECRET $PRISMA_SECRET
ENV JWT_SECRET $JWT_SECRET

RUN npm set unsafe-perm true
RUN npm install

EXPOSE 4000

CMD ["npm", "start"]
