FROM docker:18.09

RUN apk update && apk add nodejs npm python python-dev py-pip dos2unix bash build-base libffi-dev openssl-dev && pip install docker-compose

WORKDIR /app
COPY . /app
RUN find . -type f -print0 | xargs -0 dos2unix

RUN npm set unsafe-perm true && npm install --no-optional --production

VOLUME /app/server/testsets
VOLUME /app/server/botiumwork
VOLUME /app/agent/botiumwork

EXPOSE 4000

CMD npx npm-run-all -p start-standalone:backend start-standalone:frontend:docker
